apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: usersapi-deployment
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usersapi-deployment
  targetCPUUtilizationPercentage: 70